import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import NavBar from "./components/NavBar";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="ms-20 me-20 mt-5">
        <Theme>
          <NavBar />

          {children}
        </Theme>
      </body>
    </html>
  );
}
